[project]
name = "eshmun"
version = "0.1.0"
description = "Eshmun is a series of Protein Language Models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
project-excludes = [
    "notebooks/**",
]
